// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsLPmEljrgRu4NiDIU8v2QGIlsCaZF9Q',
    appId: '1:812102179149:web:0a306d7c5032c374bc7f04',
    messagingSenderId: '812102179149',
    projectId: 'asset-management-10cc0',
    authDomain: 'asset-management-10cc0.firebaseapp.com',
    storageBucket: 'asset-management-10cc0.appspot.com',
    measurementId: 'G-9RK7SZQKBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6pmpA1W36lfHNB6X2vyladH9ivhyT_4w',
    appId: '1:812102179149:android:a72ac3f4401dbb2bbc7f04',
    messagingSenderId: '812102179149',
    projectId: 'asset-management-10cc0',
    storageBucket: 'asset-management-10cc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD10_Ata_AJcHciKl84OYICeMps8VTZets',
    appId: '1:812102179149:ios:1056f5734f8cc073bc7f04',
    messagingSenderId: '812102179149',
    projectId: 'asset-management-10cc0',
    storageBucket: 'asset-management-10cc0.appspot.com',
    iosBundleId: 'com.example.myCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD10_Ata_AJcHciKl84OYICeMps8VTZets',
    appId: '1:812102179149:ios:1056f5734f8cc073bc7f04',
    messagingSenderId: '812102179149',
    projectId: 'asset-management-10cc0',
    storageBucket: 'asset-management-10cc0.appspot.com',
    iosBundleId: 'com.example.myCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdsLPmEljrgRu4NiDIU8v2QGIlsCaZF9Q',
    appId: '1:812102179149:web:a323d3be7d718280bc7f04',
    messagingSenderId: '812102179149',
    projectId: 'asset-management-10cc0',
    authDomain: 'asset-management-10cc0.firebaseapp.com',
    storageBucket: 'asset-management-10cc0.appspot.com',
    measurementId: 'G-GN0PHJ0FBH',
  );
}